#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Applying database migrations..."
alembic upgrade head

echo "Starting Django development server..."
uvicorn app.main:app --reload --port 8000 --host 0.0.0.0
