#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

/opt/venv/bin/python3 manage.py migrate
/opt/venv/bin/python3 /app/manage.py collectstatic --noinput
/opt/venv/bin/python3 manage.py runserver 0.0.0.0:8000