# Generated by Django 4.2.2 on 2024-08-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_shoppinglist_shoppingitem_shopping_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
